[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
name = "mysql_common"
description = "MySql protocol primitives"
license = "MIT/Apache-2.0"
homepage = "https://github.com/blackbeam/rust_mysql_common"
documentation = "https://docs.rs/mysql_common"
repository = "https://github.com/blackbeam/rust_mysql_common"
keywords = ["mysql", "database"]
categories = ["database"]
version = "0.7.0"

[dependencies]
atoi = "0.2"
bitflags = "1"
bit-vec = "0.5"
byteorder = "1"
chrono = "0.4"
lazy_static = "1.0"
regex = "1.0"
sha1 = "0.6"
smallvec = "0.6"
time = "0.1"
twox-hash = "1"
uuid = "0.6"
serde = "1"
serde_json = "1"

[dependencies.rustc-serialize]
version = "0.3"
optional= true

[features]
default = []
rustc_serialize = ["rustc-serialize"]
