[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
name = "mysql_common"
description = "MySql protocol primitives"
license = "MIT/Apache-2.0"
homepage = "https://github.com/blackbeam/rust_mysql_common"
documentation = "https://docs.rs/mysql_common"
repository = "https://github.com/blackbeam/rust_mysql_common"
keywords = ["mysql", "database"]
categories = ["database"]
version = "0.25.0"
edition = "2018"

[badges]
travis-ci = { repository = "blackbeam/rust_mysql_common" }

[dependencies]
base64 = "0.13"
bigdecimal = { version = "0.2", features = ["serde"] }
bitflags = "1"
byteorder = "1"
bytes = "0.6.0"
chrono = { version = "0.4", features = ["serde"] }
flate2 = { version = "1.0", default-features = false }
lazy_static = "1"
lexical = "5.2"
num-bigint = { version = "0.3" }
num-traits = { version = "0.2", features = ["i128"] }
rand = "0.7"
regex = "1"
rust_decimal = "1.0"
sha1 = "0.6"
sha2 = "0.9"
time = { version = "0.2", default-features = false, features = ["std"] }
twox-hash = "1"
uuid = "0.8"
serde = "1"
serde_json = "1"

[dev-dependencies]
proptest = "0.10.1"

[profile.bench]
debug = true

[features]
default = ["flate2/zlib"]
nightly = []
